permissions:
  contents: write

name: Update & Deploy Data Dictionary

on:
  schedule:
    - cron: '0 6 * * *'   # runs daily at 6 AM UTC
  workflow_dispatch:       # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          USE_LOCAL: 'true'
          CSV_URL: ${{ secrets.CSV_URL }}
        run: python update_data_dictionary.py

      - name: Save latest CSV to docs folder
        run: |
          mkdir -p docs
          cp output/data_dictionary.csv docs/latest_data_dictionary.csv

      - name: Commit latest CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/latest_data_dictionary.csv
          git commit -m "Update latest data dictionary CSV" || echo "No changes to commit"
          git push

      - name: Deploy MkDocs site
        run: mkdocs gh-deploy --force

      - name: Create and push version tag
        run: |
          VERSION="v$(date +'%Y.%m.%d-%H%M')"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
